name: VM Actions matrix
description: VM Actions matrix template

inputs:
  run:
    description: The CI command to run
    required: true

runs:
  using: composite
  steps:
    - uses: ${VMACTIONS}
      with:
        usesh: true
        copyback: false
        run: ${{inputs.run}}