name: BSD

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: .github/workflows/bsd.sh

    - name: Test
      uses: cross-platform-actions/action@v0.22.0
      with:
        operating_system: freebsd
        version: '13.2'
        memory: 8G
        shell: bash
        sync_files: runner-to-vm
        run: source test.sh
